name: PR Validation/Push (CI + Build)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.55

      - name: Run Go tests
        run: go test -v ./...

  build-images:
    needs: ci-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build api-service image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/api-service/Dockerfile
          push: false
          load: true
          tags: local/api-service:pr-${{ github.event.pull_request.number }}

      - name: Build checker-worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/worker-service/Dockerfile
          push: false
          load: true
          tags: local/checker-worker:pr-${{ github.event.pull_request.number }}
